apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-deploy
spec:
  selector:
    matchLabels:
      app: poll-app
  template:
    metadata:
      labels:
        app: poll-app
    spec:
      containers:
      - name: poll-container
        image: poll-image
        ports:
        - containerPort: 8000
          protocol: TCP
