apiVersion: apps/v1
kind: Deployment
metadata:  
  name: poll-deploy
spec:  
  replicas: 3  
  strategy:    
    type: RollingUpdate
    rollingUpdate:      
      maxSurge: 2
      maxUnavailable: 2
